Configure iptable forwarding policy for pods (#592)

diff --git a/microk8s-resources/wrappers/run-with-config-args b/microk8s-resources/wrappers/run-with-config-args
--- a/microk8s-resources/wrappers/run-with-config-args
+++ b/microk8s-resources/wrappers/run-with-config-args
@@ -10,10 +10,22 @@ app=$1
 
 if [ "${app}" = "kubelet" ]
 then
+  pod_cidr="$(cat $SNAP_DATA/args/kubelet | grep "pod-cidr" | tr "=" " "| gawk '{print $2}')"
+  if ! [ -z "$pod_cidr" ]
+  then
+    if ! iptables -C FORWARD -s "$pod_cidr" -m comment --comment "generated for MicroK8s pods" -j ACCEPT
+    then
+      # The point of "|| true" is that if for any reason this is failing we "fallback"
+      # to the previous manual approach of pointing people to the troubleshooting guide.
+      iptables -t filter -A FORWARD -s "$pod_cidr" -m comment --comment "generated for MicroK8s pods" -j ACCEPT || true
+      iptables -t filter -A FORWARD -d "$pod_cidr" -m comment --comment "generated for MicroK8s pods" -j ACCEPT || true
+    fi
+  fi
+
   # wait for containerd socket
   if grep -e "--address " $SNAP_DATA/args/containerd &> /dev/null
   then
-    socket=$(grep -e "--address " $SNAP_DATA/args/containerd | awk '{print $2}')
+    socket=$(grep -e "--address " $SNAP_DATA/args/containerd | gawk '{print $2}')
     # socket_file may be of the form ${SNAP_DATA}/containerd.sock
     # we need to replace any variables
     socket_file_expand=$(eval echo ${socket})
@@ -30,7 +42,7 @@ then
 
   # Handle non-unified cgroups https://github.com/ubuntu/microk8s/issues/519
   if [ -e /proc/$$/cgroup ] &&
-     [[ $(awk -F '[:]' '(/cpu/ && !/cpuset/) || /memory/ {print $3}' /proc/$$/cgroup | uniq | wc -l) -eq "2" ]] &&
+     [[ $(gawk -F '[:]' '(/cpu/ && !/cpuset/) || /memory/ {print $3}' /proc/$$/cgroup | uniq | wc -l) -eq "2" ]] &&
      ! grep -e "runtime-cgroups" $SNAP_DATA/args/kubelet &> /dev/null &&
      ! grep -e "kubelet-cgroups" $SNAP_DATA/args/kubelet &> /dev/null &&
      [ -e  /sys/fs/cgroup/systemd/system.slice ]
