More snapctl fixes

diff --git a/microk8s-resources/wrappers/run-containerd-with-args b/microk8s-resources/wrappers/run-containerd-with-args
--- a/microk8s-resources/wrappers/run-containerd-with-args
+++ b/microk8s-resources/wrappers/run-containerd-with-args
@@ -11,7 +11,15 @@ mkdir -p "${XDG_RUNTIME_DIR}"
 
 source $SNAP/actions/common/utils.sh
 
-apparmor_parser -r $SNAP/containerd-profile
+if [ -d "/etc/apparmor.d" ]; then
+  echo "Using a default profile template"
+  cp ${SNAP}/containerd-profile /etc/apparmor.d/cri-containerd.apparmor.d
+  echo "Reloading AppArmor profiles"
+  if ! service apparmor reload
+  then
+    echo "AppArmor profiles loading failed. AppArmor may be unavailable on this host."
+  fi
+fi
 
 app=containerd
 
