Fail gracefully in setting ufw rules

diff --git a/microk8s-resources/wrappers/run-kubelite-with-args b/microk8s-resources/wrappers/run-kubelite-with-args
--- a/microk8s-resources/wrappers/run-kubelite-with-args
+++ b/microk8s-resources/wrappers/run-kubelite-with-args
@@ -81,10 +81,13 @@ if echo $ufw | grep -q "Status: active" &&
 then
   # These succeed regardless of whether the rule exists already or not
   echo "Found enabled UFW: adding rules to allow in/out traffic on 'cali+' and 'vxlan.calico' devices"
-  ufw allow in on vxlan.calico
-  ufw allow out on vxlan.calico
-  ufw allow in on cali+
-  ufw allow out on cali+
+  if ! ufw allow in on vxlan.calico ||
+     ! ufw allow out on vxlan.calico ||
+     ! ufw allow in on cali+ ||
+     ! ufw allow out on cali+
+  then
+    echo "Failed to update UFW rules. You may want to set them manually."
+  fi
 fi
 
 # wait for containerd socket
