1.24-eksd patch (#3602)
* 1.24-eksd patch

* Update addons repo branches to 1.24-eksd

* Disable airgap test for 1.23-eksd (#3457)

* Disable airgap test

* Handle upgrade from 1.22-eksd

* Fix the airgap test for eksd

Co-authored-by: Konstantinos Tsakalozos <konstantinos.tsakalozos@canonical.com>

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -223,6 +223,19 @@ then
     need_kubelet_restart=true
 fi
 
+if is_ec2_instance
+then
+  INSTANCE_ID=$(curl -sS -m 5 http://169.254.169.254/latest/meta-data/instance-id)
+  A_ZONE=$(curl -sS -m 5 http://169.254.169.254/latest/meta-data/placement/availability-zone)
+  if [[ ! -z "$INSTANCE_ID" ]] && [[ ! -z "$A_ZONE" ]]
+  then
+    sed -i -n -e '/^--provider-id /!p' -e "\$a--provider-id aws:///$A_ZONE/$INSTANCE_ID" ${SNAP_DATA}/args/kubelet
+    cp -r --preserve=mode ${SNAP}/default-hooks/reconcile.d/10-provider-id-update ${SNAP_COMMON}/hooks/reconcile.d/
+    touch "${SNAP_DATA}/var/lock/providerid-needs-update"
+    need_kubelet_restart=true
+  fi
+fi
+
 # With v1.15 allow-privileged is removed from kubelet
 if grep -e "\-\-allow-privileged" ${SNAP_DATA}/args/kubelet
 then
@@ -637,6 +650,35 @@ fi
 if [ -e "${SNAP_DATA}/var/lock/no-flanneld" ]
 then
   touch "${SNAP_DATA}/var/lock/cni-needs-reload"
+fi
+
+# Configure the API sever to talk to the external dqlite
+if [ -e ${SNAP}/default-args/k8s-dqlite ] &&
+   grep -e "\-\-storage-backend=dqlite" ${SNAP_DATA}/args/kube-apiserver
+then
+  echo "Reconfiguring the API server for dqlite"
+  cp ${SNAP}/default-args/k8s-dqlite ${SNAP_DATA}/args/k8s-dqlite
+  cp ${SNAP}/default-args/k8s-dqlite-env ${SNAP_DATA}/args/k8s-dqlite-env
+  need_api_restart=true
+  if [ -e ${SNAP_DATA}/var/lock/lite.lock ]
+  then
+    snapctl stop ${SNAP_NAME}.daemon-kubelite
+  else
+    echo "Unable to restart service"
+    exit 1
+  fi
+
+  refresh_opt_in_local_config etcd-servers unix://\${SNAP_DATA}/var/kubernetes/backend/kine.sock:12379 kube-apiserver
+  $SNAP/bin/sed -i '/\-\-storage\-backend=dqlite/d' ${SNAP_DATA}/args/kube-apiserver
+
+  storage_dir="$(get_opt_in_config '--storage-dir' 'kube-apiserver')"
+  if ! [ -z $storage_dir ]
+  then
+    refresh_opt_in_local_config storage-dir "$storage_dir" k8s-dqlite
+  fi
+  $SNAP/bin/sed -i '/\-\-storage\-dir/d' ${SNAP_DATA}/args/kube-apiserver
+
+  snapctl restart ${SNAP_NAME}.daemon-k8s-dqlite
 fi
 
 # Restart reconfigured services
