Strict patch

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -2,7 +2,17 @@
 
 set -eux
 
+if [ ! -f "${SNAP_DATA}/var/lock/installed.lock" ]
+then
+  exit 0
+fi
+
 source $SNAP/actions/common/utils.sh
+
+ARCH="$($SNAP/bin/uname -m)"
+export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
+
+check_snap_interfaces # Check for interfaces but do not start until this script has run.
 
 need_api_restart=false
 need_proxy_restart=false
@@ -344,18 +354,16 @@ do
   chmod -R o-rwX ${dir}
 done
 
-# Try to create the microk8s group. Do not fail the installation if something goes wrong
-if ! getent group microk8s >/dev/null 2>&1
+# Try to create the snap_microk8s group. Do not fail the installation if something goes wrong
+if ! getent group snap_microk8s >/dev/null 2>&1
 then
-  groupadd --system microk8s || true
+  groupadd --system snap_microk8s || true
 fi
 
-if getent group microk8s >/dev/null 2>&1
+if getent group snap_microk8s >/dev/null 2>&1
 then
-  chgrp microk8s -R ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ ${SNAP_DATA}/tmp/ || true
+  chgrp snap_microk8s -R ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ ${SNAP_DATA}/tmp/ || true
 fi
-
-try_copy_users_to_snap_microk8s
 
 if ! [ -e "${SNAP_DATA}/opt/cni/bin/flanneld" ]
 then
@@ -600,6 +608,8 @@ fi
 # Refresh calico if needed
 refresh_calico_if_needed
 
+enable_snap
+
 # Restart reconfigured services
 if ${need_api_restart} ||
    ${need_proxy_restart} ||
@@ -650,3 +660,4 @@ then
     fi
   fi
 fi
+
