Disable airgap test for 1.23-eksd (#3457)
* Disable airgap test

* Handle upgrade from 1.22-eksd

* Fix the airgap test for eksd

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -623,6 +623,35 @@ then
   touch "${SNAP_DATA}/var/lock/cni-needs-reload"
 fi
 
+# Configure the API sever to talk to the external dqlite
+if [ -e ${SNAP}/default-args/k8s-dqlite ] &&
+   grep -e "\-\-storage-backend=dqlite" ${SNAP_DATA}/args/kube-apiserver
+then
+  echo "Reconfiguring the API server for dqlite"
+  cp ${SNAP}/default-args/k8s-dqlite ${SNAP_DATA}/args/k8s-dqlite
+  cp ${SNAP}/default-args/k8s-dqlite-env ${SNAP_DATA}/args/k8s-dqlite-env
+  need_api_restart=true
+  if [ -e ${SNAP_DATA}/var/lock/lite.lock ]
+  then
+    snapctl stop ${SNAP_NAME}.daemon-kubelite
+  else
+    echo "Unable to restart service"
+    exit 1
+  fi
+
+  refresh_opt_in_local_config etcd-servers unix://\${SNAP_DATA}/var/kubernetes/backend/kine.sock:12379 kube-apiserver
+  $SNAP/bin/sed -i '/\-\-storage\-backend=dqlite/d' ${SNAP_DATA}/args/kube-apiserver
+
+  storage_dir="$(get_opt_in_config '--storage-dir' 'kube-apiserver')"
+  if ! [ -z $storage_dir ]
+  then
+    refresh_opt_in_local_config storage-dir "$storage_dir" k8s-dqlite
+  fi
+  $SNAP/bin/sed -i '/\-\-storage\-dir/d' ${SNAP_DATA}/args/kube-apiserver
+
+  snapctl restart ${SNAP_NAME}.daemon-k8s-dqlite
+fi
+
 # Restart reconfigured services
 if ${need_api_restart} ||
    ${need_proxy_restart} ||
