Create the group

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -267,9 +267,15 @@ do
   chmod -R o-rwX ${dir}
 done
 
+# Try to greate the microk8s group. DO not fail the installation if something goes wrong
+if ! getent group microk8s >/dev/null 2>&1
+then
+  groupadd --system microk8s || true
+fi
+
 if getent group microk8s >/dev/null 2>&1
 then
-  chgrp microk8s -R ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/
+  chgrp microk8s -R ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ || true
 fi
 
 if grep -e "etcd.socket:2379" ${SNAP_DATA}/args/etcd
