Update nvidia-container-runtime to 3.2.0

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -278,24 +278,6 @@ then
   snapctl restart ${SNAP_NAME}.daemon-controller-manager
 fi
 
-# Securing important directories
-for dir in "${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock"
-do
-  chmod -R ug+rwX ${dir}
-  chmod -R o-rwX ${dir}
-done
-
-# Try to greate the microk8s group. DO not fail the installation if something goes wrong
-if ! getent group microk8s >/dev/null 2>&1
-then
-  groupadd --system microk8s || true
-fi
-
-if getent group microk8s >/dev/null 2>&1
-then
-  chgrp microk8s -R ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ || true
-fi
-
 if ! [ -L "${SNAP_DATA}/opt/cni/bin/flanneld" ]
 then
   # cover situation where cilium was installed prior to this update
@@ -421,4 +403,32 @@ if grep -e "\-\-cluster-cidr=10.152.183.0/24" ${SNAP_DATA}/args/kube-proxy
 then
   refresh_opt_in_config cluster-cidr 10.1.0.0/16 kube-proxy
   snapctl restart ${SNAP_NAME}.daemon-proxy
+fi
+
+# The nvidia runtime configuration file pointing to the right paths
+if [ -e ${SNAP_DATA}/args/nvidia-container-runtime ]
+then
+  cp -r $SNAP/default-args/nvidia-container-runtime ${SNAP_DATA}/args/
+  if [ -e ${SNAP_DATA}/var/lock/gpu ]
+  then
+    snapctl restart ${SNAP_NAME}.daemon-containerd
+  fi
+fi
+
+# Securing important directories
+for dir in ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock
+do
+  chmod -R ug+rwX ${dir}
+  chmod -R o-rwX ${dir}
+done
+
+# Try to greate the microk8s group. DO not fail the installation if something goes wrong
+if ! getent group microk8s >/dev/null 2>&1
+then
+  groupadd --system microk8s || true
+fi
+
+if getent group microk8s >/dev/null 2>&1
+then
+  chgrp microk8s -R ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ || true
 fi
