Strict patch

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -2,7 +2,14 @@
 
 set -eux
 
+if [ ! -f "${SNAP_DATA}/var/lock/installed.lock" ]
+then
+  exit 0
+fi
+
 source $SNAP/actions/common/utils.sh
+
+check_snap_interfaces 0  # Check for interfaces but do not start until this script has run.
 
 need_api_restart=false
 need_proxy_restart=false
@@ -191,7 +198,7 @@ then
   ISTIO_ERSION=$(echo $ISTIO_VERSION | sed 's/v//g')
   mkdir -p "${SNAP_DATA}/tmp/istio"
   (cd "${SNAP_DATA}/tmp/istio"
-  "${SNAP}/usr/bin/curl" -L https://github.com/istio/istio/releases/download/${ISTIO_ERSION}/istio-${ISTIO_ERSION}-linux.tar.gz -o "$SNAP_DATA/tmp/istio/istio.tar.gz"
+  curl -L https://github.com/istio/istio/releases/download/${ISTIO_ERSION}/istio-${ISTIO_ERSION}-linux.tar.gz -o "$SNAP_DATA/tmp/istio/istio.tar.gz"
   gzip -d "$SNAP_DATA/tmp/istio/istio.tar.gz"
   tar -xvf "$SNAP_DATA/tmp/istio/istio.tar")
   mkdir -p "$SNAP_DATA/bin/"
@@ -333,21 +340,22 @@ then
   mv ${CD_TOML_TMP} ${CD_TOML}
 fi
 
-for dir in ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/
+# Securing important directories
+for dir in ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/
 do
   chmod -R ug+rwX ${dir}
   chmod -R o-rwX ${dir}
 done
 
-# Try to create the microk8s group. Do not fail the installation if something goes wrong
-if ! getent group microk8s >/dev/null 2>&1
+# Try to create the snap_microk8s group. Do not fail the installation if something goes wrong
+if ! getent group snap_microk8s >/dev/null 2>&1
 then
-  groupadd --system microk8s || true
+  groupadd --system snap_microk8s || true
 fi
 
-if getent group microk8s >/dev/null 2>&1
+if getent group snap_microk8s >/dev/null 2>&1
 then
-  chgrp microk8s -R ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ ${SNAP_DATA}/tmp/ || true
+  chgrp snap_microk8s -R ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock/ ${SNAP_DATA}/var/kubernetes/backend/ ${SNAP_DATA}/tmp/ || true
 fi
 
 try_copy_users_to_snap_microk8s
@@ -640,3 +648,5 @@ then
     fi
   fi
 fi
+
+check_snap_interfaces 1  # Check for interfaces and enable all services.
