Fail installation on LXD if profiles are missing

diff --git a/snap/hooks/install b/snap/hooks/install
--- a/snap/hooks/install
+++ b/snap/hooks/install
@@ -14,6 +14,20 @@ export LD_LIBRARY_PATH="${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/lib/$ARCH-linux-gnu:
 export PATH="${SNAP}/usr/sbin:${SNAP}/usr/bin:${SNAP}/sbin:${SNAP}/bin:$PATH:/usr/bin:/usr/local/bin"
 export OPENSSL_CONF="${SNAP}/etc/ssl/openssl.cnf"
 
+# LXD Specific Checks
+if ! is_strict && cat /proc/1/environ | grep "container=lxc" &> /dev/null
+  then
+
+  # make sure the /dev/kmsg is available, indicating a potential missing profile
+  if [ ! -c "/dev/kmsg" ]  # kmsg is a character device
+  then
+    printf -- '\e[1;31mERROR: \033[0m the lxc profile for MicroK8s might be missing. \n'
+    printf -- '\t  Refer to this help document to get MicroK8s working in with LXD: \n'
+    printf -- '\t  https://microk8s.io/docs/lxd \n'
+    exit 1
+  fi
+fi
+
 cp -r --preserve=mode ${SNAP}/default-args ${SNAP_DATA}/args
 mv ${SNAP_DATA}/args/certs.d/localhost__32000 ${SNAP_DATA}/args/certs.d/localhost:32000
 
