Added strict checks and combined strict/classic logic to remove hook

diff --git a/snap/hooks/remove b/snap/hooks/remove
--- a/snap/hooks/remove
+++ b/snap/hooks/remove
@@ -11,7 +11,10 @@ then
 else
   snapctl stop ${SNAP_NAME}.daemon-kubelet 2>&1 || true
 fi
-snapctl stop ${SNAP_NAME}.daemon-docker 2>&1 || true
+if ! is_strict
+then
+  snapctl stop ${SNAP_NAME}.daemon-docker 2>&1 || true
+fi
 
 # Sym link the host's /var/lib/kubelet to the Snap's.  This will be fixed with layouts when
 # this Snap is strictly confined.
@@ -52,21 +55,41 @@ rm -rf ${SNAP_COMMON}/run/containerd/* || true
 (cat /proc/mounts | grep ${SNAP_COMMON}/var/run/docker | cut -d ' ' -f 2 | xargs umount) || true
 (cat /proc/mounts | grep ${SNAP_COMMON}/var/lib/kubelet | cut -d ' ' -f 2 | xargs umount) || true
 
-if $SNAP/sbin/ip link show cni0
+if is_strict
 then
-  $SNAP/sbin/ip link delete cni0
+  if snapctl is-connected network-control
+  then
+    for link in cni0 cilium_vxlan
+    do
+      if $SNAP/sbin/ip link show ${link}
+      then
+        $SNAP/sbin/ip link delete ${link}
+      fi
+    done
+  fi
+else
+  if $SNAP/sbin/ip link show cni0
+  then
+    $SNAP/sbin/ip link delete cni0
+  fi
 fi
 
-kill_all_container_shims
-
-# Cleanup calico interface.
-if "${SNAP}/sbin/ip" link show vxlan.calico
+if is_strict
 then
-  "${SNAP}/sbin/ip" link delete vxlan.calico || true
-fi
+  remove_all_containers
 
-# Cleanup cni network namespaces.
-for ns in `"${SNAP}/sbin/ip" netns list | grep "^cni-" | awk '{print $1}'`
-do
-  $SNAP/sbin/ip netns delete "${ns}" || true
-done
+else
+  kill_all_container_shims
+
+  # Cleanup calico interface.
+  if "${SNAP}/sbin/ip" link show vxlan.calico
+  then
+    "${SNAP}/sbin/ip" link delete vxlan.calico || true
+  fi
+
+  # Cleanup cni network namespaces.
+  for ns in `"${SNAP}/sbin/ip" netns list | grep "^cni-" | awk '{print $1}'`
+  do
+    $SNAP/sbin/ip netns delete "${ns}" || true
+  done
+fi
