Moved network cleanup out of classic block and removed unnecessary strict check

diff --git a/snap/hooks/remove b/snap/hooks/remove
--- a/snap/hooks/remove
+++ b/snap/hooks/remove
@@ -11,10 +11,7 @@ then
 else
   snapctl stop ${SNAP_NAME}.daemon-kubelet 2>&1 || true
 fi
-if ! is_strict
-then
-  snapctl stop ${SNAP_NAME}.daemon-docker 2>&1 || true
-fi
+snapctl stop ${SNAP_NAME}.daemon-docker 2>&1 || true
 
 # Sym link the host's /var/lib/kubelet to the Snap's.  This will be fixed with layouts when
 # this Snap is strictly confined.
@@ -77,19 +74,18 @@ fi
 if is_strict
 then
   remove_all_containers
-
 else
   kill_all_container_shims
-
-  # Cleanup calico interface.
-  if "${SNAP}/sbin/ip" link show vxlan.calico
-  then
-    "${SNAP}/sbin/ip" link delete vxlan.calico || true
-  fi
-
-  # Cleanup cni network namespaces.
-  for ns in `"${SNAP}/sbin/ip" netns list | grep "^cni-" | awk '{print $1}'`
-  do
-    $SNAP/sbin/ip netns delete "${ns}" || true
-  done
 fi
+
+# Cleanup calico interface.
+if "${SNAP}/sbin/ip" link show vxlan.calico
+then
+  "${SNAP}/sbin/ip" link delete vxlan.calico || true
+fi
+
+# Cleanup cni network namespaces.
+for ns in `"${SNAP}/sbin/ip" netns list | grep "^cni-" | awk '{print $1}'`
+do
+  $SNAP/sbin/ip netns delete "${ns}" || true
+done
